const translations = {
  id: {
    nav_templates: 'Template', nav_create: 'Buat Invoice',
    hero_title: '100+ Template Invoice Gratis',
    hero_subtitle: 'Buat invoice profesional dalam hitungan menit. Pilih desain, isi data, langsung kirim.',
    hero_cta: 'Buat Invoice Sekarang!',
    gallery_title: 'Pilih Desain Invoice Kamu', gallery_subtitle: 'Mulai membuat invoice profesional dari sini!',
    see_all: 'Lihat Semua Template',
    f1_title: 'Buat Invoice', f1_desc: 'Pilih dari banyak template, tambahkan logo perusahaanmu.',
    f2_title: 'Kirim via Email', f2_desc: 'Kirim sebagai PDF langsung ke klien, atau cetak.',
    f3_title: 'Terima Pembayaran', f3_desc: 'Dapatkan pembayaran lebih cepat secara online.',
    footer: 'Dibuat untuk tugas kelompok — InvoiceKita 2026',
    tp_title: 'Pilih Template Invoice', tp_subtitle: '10 desain profesional, gratis untuk dipakai.',
    use_template: 'Gunakan template →',
    et_title: 'Buat Invoice', et_info: 'Info Dasar', et_invoice_number: 'No. Invoice', et_status: 'Status',
    et_status_unpaid: 'Belum Dibayar', et_status_paid: 'Lunas', et_status_overdue: 'Terlambat',
    et_issue_date: 'Tanggal Terbit', et_due_date: 'Jatuh Tempo',
    et_from: 'Dari (Perusahaan Kamu)', et_to: 'Kepada (Klien)',
    et_company_name: 'Nama perusahaan', et_address: 'Alamat', et_email: 'Email', et_phone: 'Telepon',
    et_client_name: 'Nama klien', et_items: 'Item', et_add_item: '+ Tambah Item',
    et_description: 'Deskripsi', et_qty: 'Qty', et_price: 'Harga',
    et_tax: 'Pajak (%)', et_discount: 'Diskon (%)', et_notes: 'Catatan',
    tpl1_name: 'Neat Minimal', tpl1_desc: 'Simpel & bersih, cocok untuk bisnis modern',
    tpl2_name: 'Classic Corporate', tpl2_desc: 'Formal, cocok untuk perusahaan besar',
    tpl3_name: 'Bold Band', tpl3_desc: 'Warna cerah & berani, menarik perhatian',
    tpl4_name: 'Modern Gradient', tpl4_desc: 'Gradasi warna, kesan kreatif & fresh',
    tpl5_name: 'Dark Studio', tpl5_desc: 'Tema gelap, cocok untuk studio digital/tech',
    tpl6_name: 'Elegant Luxury', tpl6_desc: 'Emas & elegan, kesan premium',
    tpl7_name: 'Creative Asymmetric', tpl7_desc: 'Layout split unik, cocok untuk agensi kreatif',
    tpl8_name: 'Nature Eco', tpl8_desc: 'Hijau & natural, untuk bisnis ramah lingkungan',
    tpl9_name: 'Tech Startup', tpl9_desc: 'Gaya SaaS modern, untuk perusahaan teknologi',
    tpl10_name: 'Freelance', tpl10_desc: 'Playful & personal, cocok untuk freelancer',
    tpl23_name: 'Curved Teal', tpl23_desc: 'Header melengkung, gaya hangat',
    tpl24_name: 'Pixel Receipt', tpl24_desc: 'Struk monospace, tepi bergerigi',
    tpl25_name: 'Ledger Klasik', tpl25_desc: 'Gaya buku kas akuntansi lama',
    tpl26_name: 'Swiss Grid', tpl26_desc: 'Grid tegas ala desain Swiss',
    tpl27_name: 'Motif Warm', tpl27_desc: 'Indigo & emas, kesan mewah',
    tpl28_name: 'Minimalis Mono', tpl28_desc: 'Nyaris tanpa warna, fokus tipografi',
    tpl29_name: 'Studio Hitam', tpl29_desc: 'Hitam pekat, garis putih tegas',
    tpl30_name: 'Brutalist Bracket', tpl30_desc: 'Flat & tegas, gaya brutalist',
    tpl31_name: 'Editorial Merah', tpl31_desc: 'Headline merah besar ala majalah',
    tpl32_name: 'Sidebar Biru', tpl32_desc: 'Sidebar biru solid untuk identitas',
  },
  en: {
    nav_templates: 'Templates', nav_create: 'Create Invoice',
    hero_title: '100+ Free Invoice Templates',
    hero_subtitle: 'Create a professional invoice in minutes. Pick a design, fill in the details, send it.',
    hero_cta: 'Create Invoice Now!',
    gallery_title: 'Choose Your Invoice Design', gallery_subtitle: 'Start creating your professional invoice here!',
    see_all: 'See All Templates',
    f1_title: 'Create an Invoice', f1_desc: 'Choose from many templates and add your company logo.',
    f2_title: 'Send via Email', f2_desc: 'Send as a PDF directly to your client, or print it.',
    f3_title: 'Get Paid', f3_desc: 'Receive payments faster online.',
    footer: 'Made for a group project — InvoiceKita 2026',
    tp_title: 'Choose an Invoice Template', tp_subtitle: '10 professional designs, free to use.',
    use_template: 'Use this template →',
    et_title: 'Create Invoice', et_info: 'Basic Info', et_invoice_number: 'Invoice No.', et_status: 'Status',
    et_status_unpaid: 'Unpaid', et_status_paid: 'Paid', et_status_overdue: 'Overdue',
    et_issue_date: 'Issue Date', et_due_date: 'Due Date',
    et_from: 'From (Your Company)', et_to: 'To (Client)',
    et_company_name: 'Company name', et_address: 'Address', et_email: 'Email', et_phone: 'Phone',
    et_client_name: 'Client name', et_items: 'Items', et_add_item: '+ Add Item',
    et_description: 'Description', et_qty: 'Qty', et_price: 'Price',
    et_tax: 'Tax (%)', et_discount: 'Discount (%)', et_notes: 'Notes',
    tpl1_name: 'Neat Minimal', tpl1_desc: 'Simple & clean, great for modern businesses',
    tpl2_name: 'Classic Corporate', tpl2_desc: 'Formal, suited for large companies',
    tpl3_name: 'Bold Band', tpl3_desc: 'Bright & bold colors that grab attention',
    tpl4_name: 'Modern Gradient', tpl4_desc: 'Color gradients, creative & fresh feel',
    tpl5_name: 'Dark Studio', tpl5_desc: 'Dark theme, great for digital/tech studios',
    tpl6_name: 'Elegant Luxury', tpl6_desc: 'Gold & elegant, premium feel',
    tpl7_name: 'Creative Asymmetric', tpl7_desc: 'Unique split layout, great for creative agencies',
    tpl8_name: 'Nature Eco', tpl8_desc: 'Green & natural, for eco-friendly businesses',
    tpl9_name: 'Tech Startup', tpl9_desc: 'Modern SaaS style, for tech companies',
    tpl10_name: 'Freelance', tpl10_desc: 'Playful & personal, great for freelancers',
    tpl23_name: 'Curved Teal', tpl23_desc: 'Curved header, warm feel',
    tpl24_name: 'Pixel Receipt', tpl24_desc: 'Monospace receipt, jagged edges',
    tpl25_name: 'Classic Ledger', tpl25_desc: 'Old-school accounting ledger style',
    tpl26_name: 'Swiss Grid', tpl26_desc: 'Bold grid, Swiss design style',
    tpl27_name: 'Warm Motif', tpl27_desc: 'Indigo & gold, luxurious feel',
    tpl28_name: 'Minimal Mono', tpl28_desc: 'Nearly colorless, typography-focused',
    tpl29_name: 'Black Studio', tpl29_desc: 'Deep black, bold white lines',
    tpl30_name: 'Brutalist Bracket', tpl30_desc: 'Flat and bold, brutalist style',
    tpl31_name: 'Red Editorial', tpl31_desc: 'Big red headline, magazine style',
    tpl32_name: 'Blue Sidebar', tpl32_desc: 'Solid blue sidebar for identity',
  },
  es: {
    nav_templates: 'Plantillas', nav_create: 'Crear Factura',
    hero_title: '100+ Plantillas de Factura Gratis',
    hero_subtitle: 'Crea una factura profesional en minutos. Elige un diseño, completa los datos, envíala.',
    hero_cta: '¡Crear Factura Ahora!',
    gallery_title: 'Elige tu Diseño de Factura', gallery_subtitle: '¡Empieza a crear tu factura profesional aquí!',
    see_all: 'Ver Todas las Plantillas',
    f1_title: 'Crea una Factura', f1_desc: 'Elige entre varias plantillas y añade el logo de tu empresa.',
    f2_title: 'Envía por Email', f2_desc: 'Envía como PDF directamente a tu cliente, o imprímela.',
    f3_title: 'Recibe Pagos', f3_desc: 'Recibe pagos más rápido en línea.',
    footer: 'Hecho para un proyecto grupal — InvoiceKita 2026',
    tp_title: 'Elige una Plantilla de Factura', tp_subtitle: '10 diseños profesionales, gratis para usar.',
    use_template: 'Usar esta plantilla →',
    et_title: 'Crear Factura', et_info: 'Información Básica', et_invoice_number: 'N.º de Factura', et_status: 'Estado',
    et_status_unpaid: 'Sin Pagar', et_status_paid: 'Pagada', et_status_overdue: 'Vencida',
    et_issue_date: 'Fecha de Emisión', et_due_date: 'Fecha de Vencimiento',
    et_from: 'De (Tu Empresa)', et_to: 'Para (Cliente)',
    et_company_name: 'Nombre de la empresa', et_address: 'Dirección', et_email: 'Email', et_phone: 'Teléfono',
    et_client_name: 'Nombre del cliente', et_items: 'Artículos', et_add_item: '+ Añadir Artículo',
    et_description: 'Descripción', et_qty: 'Cant.', et_price: 'Precio',
    et_tax: 'Impuesto (%)', et_discount: 'Descuento (%)', et_notes: 'Notas',
    tpl1_name: 'Neat Minimal', tpl1_desc: 'Simple y limpio, ideal para negocios modernos',
    tpl2_name: 'Classic Corporate', tpl2_desc: 'Formal, adecuado para grandes empresas',
    tpl3_name: 'Bold Band', tpl3_desc: 'Colores vivos y llamativos',
    tpl4_name: 'Modern Gradient', tpl4_desc: 'Degradados de color, sensación creativa',
    tpl5_name: 'Dark Studio', tpl5_desc: 'Tema oscuro, ideal para estudios tech',
    tpl6_name: 'Elegant Luxury', tpl6_desc: 'Dorado y elegante, sensación premium',
    tpl7_name: 'Creative Asymmetric', tpl7_desc: 'Diseño dividido único, para agencias creativas',
    tpl8_name: 'Nature Eco', tpl8_desc: 'Verde y natural, para negocios ecológicos',
    tpl9_name: 'Tech Startup', tpl9_desc: 'Estilo SaaS moderno, para empresas tech',
    tpl10_name: 'Freelance', tpl10_desc: 'Divertido y personal, ideal para freelancers',
  },
  fr: {
    nav_templates: 'Modèles', nav_create: 'Créer une Facture',
    hero_title: '100+ Modèles de Facture Gratuits',
    hero_subtitle: 'Créez une facture professionnelle en quelques minutes. Choisissez un modèle, remplissez les détails, envoyez-la.',
    hero_cta: 'Créer une Facture Maintenant !',
    gallery_title: 'Choisissez votre Modèle de Facture', gallery_subtitle: 'Commencez à créer votre facture professionnelle ici !',
    see_all: 'Voir Tous les Modèles',
    f1_title: 'Créer une Facture', f1_desc: 'Choisissez parmi de nombreux modèles et ajoutez le logo de votre entreprise.',
    f2_title: 'Envoyer par Email', f2_desc: 'Envoyez en PDF directement à votre client, ou imprimez-la.',
    f3_title: 'Soyez Payé', f3_desc: 'Recevez des paiements plus rapidement en ligne.',
    footer: 'Réalisé pour un projet de groupe — InvoiceKita 2026',
    tp_title: 'Choisissez un Modèle de Facture', tp_subtitle: '10 designs professionnels, gratuits à utiliser.',
    use_template: 'Utiliser ce modèle →',
    et_title: 'Créer une Facture', et_info: 'Infos de Base', et_invoice_number: 'N° de Facture', et_status: 'Statut',
    et_status_unpaid: 'Non Payée', et_status_paid: 'Payée', et_status_overdue: 'En Retard',
    et_issue_date: "Date d'Émission", et_due_date: "Date d'Échéance",
    et_from: 'De (Votre Entreprise)', et_to: 'À (Client)',
    et_company_name: "Nom de l'entreprise", et_address: 'Adresse', et_email: 'Email', et_phone: 'Téléphone',
    et_client_name: 'Nom du client', et_items: 'Articles', et_add_item: '+ Ajouter un Article',
    et_description: 'Description', et_qty: 'Qté', et_price: 'Prix',
    et_tax: 'Taxe (%)', et_discount: 'Remise (%)', et_notes: 'Notes',
    tpl1_name: 'Neat Minimal', tpl1_desc: 'Simple et épuré, pour les entreprises modernes',
    tpl2_name: 'Classic Corporate', tpl2_desc: 'Formel, adapté aux grandes entreprises',
    tpl3_name: 'Bold Band', tpl3_desc: 'Couleurs vives et audacieuses',
    tpl4_name: 'Modern Gradient', tpl4_desc: 'Dégradés de couleur, esprit créatif',
    tpl5_name: 'Dark Studio', tpl5_desc: 'Thème sombre, pour studios tech',
    tpl6_name: 'Elegant Luxury', tpl6_desc: 'Doré et élégant, sensation premium',
    tpl7_name: 'Creative Asymmetric', tpl7_desc: 'Mise en page originale, pour agences créatives',
    tpl8_name: 'Nature Eco', tpl8_desc: 'Vert et naturel, pour entreprises écologiques',
    tpl9_name: 'Tech Startup', tpl9_desc: 'Style SaaS moderne, pour entreprises tech',
    tpl10_name: 'Freelance', tpl10_desc: 'Ludique et personnel, pour freelances',
  },
  de: {
    nav_templates: 'Vorlagen', nav_create: 'Rechnung Erstellen',
    hero_title: '100+ Kostenlose Rechnungsvorlagen',
    hero_subtitle: 'Erstellen Sie in wenigen Minuten eine professionelle Rechnung. Design wählen, Daten eingeben, senden.',
    hero_cta: 'Jetzt Rechnung Erstellen!',
    gallery_title: 'Wählen Sie Ihr Rechnungsdesign', gallery_subtitle: 'Beginnen Sie hier mit der Erstellung Ihrer professionellen Rechnung!',
    see_all: 'Alle Vorlagen Ansehen',
    f1_title: 'Rechnung Erstellen', f1_desc: 'Wählen Sie aus vielen Vorlagen und fügen Sie Ihr Firmenlogo hinzu.',
    f2_title: 'Per E-Mail Senden', f2_desc: 'Senden Sie als PDF direkt an Ihren Kunden oder drucken Sie sie aus.',
    f3_title: 'Bezahlt Werden', f3_desc: 'Erhalten Sie Zahlungen schneller online.',
    footer: 'Erstellt für ein Gruppenprojekt — InvoiceKita 2026',
    tp_title: 'Wählen Sie eine Rechnungsvorlage', tp_subtitle: '10 professionelle Designs, kostenlos nutzbar.',
    use_template: 'Vorlage verwenden →',
    et_title: 'Rechnung Erstellen', et_info: 'Grundinfos', et_invoice_number: 'Rechnungsnr.', et_status: 'Status',
    et_status_unpaid: 'Unbezahlt', et_status_paid: 'Bezahlt', et_status_overdue: 'Überfällig',
    et_issue_date: 'Ausstellungsdatum', et_due_date: 'Fälligkeitsdatum',
    et_from: 'Von (Ihr Unternehmen)', et_to: 'An (Kunde)',
    et_company_name: 'Firmenname', et_address: 'Adresse', et_email: 'E-Mail', et_phone: 'Telefon',
    et_client_name: 'Kundenname', et_items: 'Artikel', et_add_item: '+ Artikel Hinzufügen',
    et_description: 'Beschreibung', et_qty: 'Menge', et_price: 'Preis',
    et_tax: 'Steuer (%)', et_discount: 'Rabatt (%)', et_notes: 'Notizen',
    tpl1_name: 'Neat Minimal', tpl1_desc: 'Einfach & sauber, für moderne Unternehmen',
    tpl2_name: 'Classic Corporate', tpl2_desc: 'Formell, für große Unternehmen geeignet',
    tpl3_name: 'Bold Band', tpl3_desc: 'Kräftige Farben, die Aufmerksamkeit erregen',
    tpl4_name: 'Modern Gradient', tpl4_desc: 'Farbverläufe, kreatives Gefühl',
    tpl5_name: 'Dark Studio', tpl5_desc: 'Dunkles Design, für Tech-Studios',
    tpl6_name: 'Elegant Luxury', tpl6_desc: 'Gold & elegant, Premium-Gefühl',
    tpl7_name: 'Creative Asymmetric', tpl7_desc: 'Einzigartiges Split-Layout, für Kreativagenturen',
    tpl8_name: 'Nature Eco', tpl8_desc: 'Grün & natürlich, für ökologische Unternehmen',
    tpl9_name: 'Tech Startup', tpl9_desc: 'Moderner SaaS-Stil, für Tech-Unternehmen',
    tpl10_name: 'Freelance', tpl10_desc: 'Verspielt & persönlich, für Freelancer',
  },
  it: {
    nav_templates: 'Modelli', nav_create: 'Crea Fattura',
    hero_title: '100+ Modelli di Fattura Gratuiti',
    hero_subtitle: 'Crea una fattura professionale in pochi minuti. Scegli un design, inserisci i dati, invia.',
    hero_cta: 'Crea Fattura Ora!',
    gallery_title: 'Scegli il tuo Design della Fattura', gallery_subtitle: 'Inizia a creare la tua fattura professionale qui!',
    see_all: 'Vedi Tutti i Modelli',
    f1_title: 'Crea una Fattura', f1_desc: 'Scegli tra molti modelli e aggiungi il logo della tua azienda.',
    f2_title: 'Invia via Email', f2_desc: 'Invia come PDF direttamente al cliente, o stampala.',
    f3_title: 'Ricevi Pagamenti', f3_desc: 'Ricevi pagamenti più velocemente online.',
    footer: 'Realizzato per un progetto di gruppo — InvoiceKita 2026',
    tp_title: 'Scegli un Modello di Fattura', tp_subtitle: '10 design professionali, gratuiti da usare.',
    use_template: 'Usa questo modello →',
    et_title: 'Crea Fattura', et_info: 'Info di Base', et_invoice_number: 'N. Fattura', et_status: 'Stato',
    et_status_unpaid: 'Non Pagata', et_status_paid: 'Pagata', et_status_overdue: 'Scaduta',
    et_issue_date: 'Data di Emissione', et_due_date: 'Data di Scadenza',
    et_from: 'Da (La Tua Azienda)', et_to: 'A (Cliente)',
    et_company_name: 'Nome azienda', et_address: 'Indirizzo', et_email: 'Email', et_phone: 'Telefono',
    et_client_name: 'Nome cliente', et_items: 'Articoli', et_add_item: '+ Aggiungi Articolo',
    et_description: 'Descrizione', et_qty: 'Qtà', et_price: 'Prezzo',
    et_tax: 'Tassa (%)', et_discount: 'Sconto (%)', et_notes: 'Note',
    tpl1_name: 'Neat Minimal', tpl1_desc: 'Semplice e pulito, per aziende moderne',
    tpl2_name: 'Classic Corporate', tpl2_desc: 'Formale, adatto a grandi aziende',
    tpl3_name: 'Bold Band', tpl3_desc: 'Colori vivaci e audaci',
    tpl4_name: 'Modern Gradient', tpl4_desc: 'Sfumature di colore, senso creativo',
    tpl5_name: 'Dark Studio', tpl5_desc: 'Tema scuro, per studi tech',
    tpl6_name: 'Elegant Luxury', tpl6_desc: 'Oro ed elegante, senso premium',
    tpl7_name: 'Creative Asymmetric', tpl7_desc: 'Layout diviso unico, per agenzie creative',
    tpl8_name: 'Nature Eco', tpl8_desc: 'Verde e naturale, per aziende ecologiche',
    tpl9_name: 'Tech Startup', tpl9_desc: 'Stile SaaS moderno, per aziende tech',
    tpl10_name: 'Freelance', tpl10_desc: 'Giocoso e personale, per freelance',
  },
  pt: {
    nav_templates: 'Modelos', nav_create: 'Criar Fatura',
    hero_title: '100+ Modelos de Fatura Grátis',
    hero_subtitle: 'Crie uma fatura profissional em minutos. Escolha um design, preencha os dados, envie.',
    hero_cta: 'Criar Fatura Agora!',
    gallery_title: 'Escolha o Design da sua Fatura', gallery_subtitle: 'Comece a criar sua fatura profissional aqui!',
    see_all: 'Ver Todos os Modelos',
    f1_title: 'Crie uma Fatura', f1_desc: 'Escolha entre vários modelos e adicione o logotipo da sua empresa.',
    f2_title: 'Envie por Email', f2_desc: 'Envie como PDF diretamente para o cliente, ou imprima.',
    f3_title: 'Receba Pagamentos', f3_desc: 'Receba pagamentos mais rápido online.',
    footer: 'Feito para um projeto em grupo — InvoiceKita 2026',
    tp_title: 'Escolha um Modelo de Fatura', tp_subtitle: '10 designs profissionais, grátis para usar.',
    use_template: 'Usar este modelo →',
    et_title: 'Criar Fatura', et_info: 'Informações Básicas', et_invoice_number: 'N.º da Fatura', et_status: 'Status',
    et_status_unpaid: 'Não Paga', et_status_paid: 'Paga', et_status_overdue: 'Atrasada',
    et_issue_date: 'Data de Emissão', et_due_date: 'Data de Vencimento',
    et_from: 'De (Sua Empresa)', et_to: 'Para (Cliente)',
    et_company_name: 'Nome da empresa', et_address: 'Endereço', et_email: 'Email', et_phone: 'Telefone',
    et_client_name: 'Nome do cliente', et_items: 'Itens', et_add_item: '+ Adicionar Item',
    et_description: 'Descrição', et_qty: 'Qtd', et_price: 'Preço',
    et_tax: 'Imposto (%)', et_discount: 'Desconto (%)', et_notes: 'Notas',
    tpl1_name: 'Neat Minimal', tpl1_desc: 'Simples e limpo, ideal para negócios modernos',
    tpl2_name: 'Classic Corporate', tpl2_desc: 'Formal, adequado para grandes empresas',
    tpl3_name: 'Bold Band', tpl3_desc: 'Cores vivas e ousadas',
    tpl4_name: 'Modern Gradient', tpl4_desc: 'Gradientes de cor, sensação criativa',
    tpl5_name: 'Dark Studio', tpl5_desc: 'Tema escuro, para estúdios tech',
    tpl6_name: 'Elegant Luxury', tpl6_desc: 'Dourado e elegante, sensação premium',
    tpl7_name: 'Creative Asymmetric', tpl7_desc: 'Layout dividido único, para agências criativas',
    tpl8_name: 'Nature Eco', tpl8_desc: 'Verde e natural, para negócios ecológicos',
    tpl9_name: 'Tech Startup', tpl9_desc: 'Estilo SaaS moderno, para empresas tech',
    tpl10_name: 'Freelance', tpl10_desc: 'Divertido e pessoal, para freelancers',
  },
  ja: {
    nav_templates: 'テンプレート', nav_create: '請求書を作成',
    hero_title: '100種類以上の無料請求書テンプレート',
    hero_subtitle: '数分でプロ仕様の請求書を作成。デザインを選んで、情報を入力し、送信するだけ。',
    hero_cta: '今すぐ請求書を作成！',
    gallery_title: '請求書デザインを選択', gallery_subtitle: 'ここからプロの請求書作成を始めましょう！',
    see_all: 'すべてのテンプレートを見る',
    f1_title: '請求書を作成', f1_desc: '多数のテンプレートから選び、会社のロゴを追加。',
    f2_title: 'メールで送信', f2_desc: 'PDFとしてクライアントに直接送信、または印刷。',
    f3_title: '支払いを受け取る', f3_desc: 'オンラインでより早く支払いを受け取れます。',
    footer: 'グループプロジェクトのために作成 — InvoiceKita 2026',
    tp_title: '請求書テンプレートを選択', tp_subtitle: '10種類のプロデザイン、無料でご利用可能。',
    use_template: 'このテンプレートを使う →',
    et_title: '請求書を作成', et_info: '基本情報', et_invoice_number: '請求書番号', et_status: 'ステータス',
    et_status_unpaid: '未払い', et_status_paid: '支払済み', et_status_overdue: '延滞',
    et_issue_date: '発行日', et_due_date: '支払期限',
    et_from: '差出人（あなたの会社）', et_to: '宛先（クライアント）',
    et_company_name: '会社名', et_address: '住所', et_email: 'メール', et_phone: '電話番号',
    et_client_name: 'クライアント名', et_items: '項目', et_add_item: '+ 項目を追加',
    et_description: '説明', et_qty: '数量', et_price: '価格',
    et_tax: '税金 (%)', et_discount: '割引 (%)', et_notes: 'メモ',
    tpl1_name: 'Neat Minimal', tpl1_desc: 'シンプルで清潔、現代的なビジネスに最適',
    tpl2_name: 'Classic Corporate', tpl2_desc: 'フォーマル、大企業向け',
    tpl3_name: 'Bold Band', tpl3_desc: '鮮やかで大胆な色使い',
    tpl4_name: 'Modern Gradient', tpl4_desc: 'グラデーション、クリエイティブな印象',
    tpl5_name: 'Dark Studio', tpl5_desc: 'ダークテーマ、テックスタジオ向け',
    tpl6_name: 'Elegant Luxury', tpl6_desc: 'ゴールドでエレガント、プレミアム感',
    tpl7_name: 'Creative Asymmetric', tpl7_desc: 'ユニークな分割レイアウト、クリエイティブ企業向け',
    tpl8_name: 'Nature Eco', tpl8_desc: 'グリーンでナチュラル、エコビジネス向け',
    tpl9_name: 'Tech Startup', tpl9_desc: 'モダンなSaaSスタイル、テック企業向け',
    tpl10_name: 'Freelance', tpl10_desc: '遊び心があり個人的、フリーランス向け',
  },
  ko: {
    nav_templates: '템플릿', nav_create: '인보이스 만들기',
    hero_title: '100개 이상의 무료 인보이스 템플릿',
    hero_subtitle: '몇 분 만에 전문적인 인보이스를 만드세요. 디자인을 선택하고, 정보를 입력하고, 바로 보내세요.',
    hero_cta: '지금 인보이스 만들기!',
    gallery_title: '인보이스 디자인 선택하기', gallery_subtitle: '여기서 전문적인 인보이스 만들기를 시작하세요!',
    see_all: '모든 템플릿 보기',
    f1_title: '인보이스 만들기', f1_desc: '다양한 템플릿 중에서 선택하고 회사 로고를 추가하세요.',
    f2_title: '이메일로 보내기', f2_desc: 'PDF로 클라이언트에게 바로 보내거나 인쇄하세요.',
    f3_title: '결제 받기', f3_desc: '온라인으로 더 빠르게 결제를 받으세요.',
    footer: '그룹 프로젝트를 위해 제작 — InvoiceKita 2026',
    tp_title: '인보이스 템플릿 선택', tp_subtitle: '10가지 전문 디자인, 무료로 사용 가능.',
    use_template: '이 템플릿 사용하기 →',
    et_title: '인보이스 만들기', et_info: '기본 정보', et_invoice_number: '인보이스 번호', et_status: '상태',
    et_status_unpaid: '미결제', et_status_paid: '결제완료', et_status_overdue: '연체',
    et_issue_date: '발행일', et_due_date: '만기일',
    et_from: '보내는 사람 (귀사)', et_to: '받는 사람 (클라이언트)',
    et_company_name: '회사명', et_address: '주소', et_email: '이메일', et_phone: '전화번호',
    et_client_name: '클라이언트명', et_items: '항목', et_add_item: '+ 항목 추가',
    et_description: '설명', et_qty: '수량', et_price: '가격',
    et_tax: '세금 (%)', et_discount: '할인 (%)', et_notes: '메모',
    tpl1_name: 'Neat Minimal', tpl1_desc: '심플하고 깔끔, 현대적인 비즈니스에 적합',
    tpl2_name: 'Classic Corporate', tpl2_desc: '격식있는 스타일, 대기업에 적합',
    tpl3_name: 'Bold Band', tpl3_desc: '밝고 대담한 색상, 시선을 끄는 디자인',
    tpl4_name: 'Modern Gradient', tpl4_desc: '그라데이션 컬러, 창의적인 느낌',
    tpl5_name: 'Dark Studio', tpl5_desc: '다크 테마, 테크 스튜디오에 적합',
    tpl6_name: 'Elegant Luxury', tpl6_desc: '골드톤의 우아함, 프리미엄 느낌',
    tpl7_name: 'Creative Asymmetric', tpl7_desc: '독특한 분할 레이아웃, 크리에이티브 에이전시에 적합',
    tpl8_name: 'Nature Eco', tpl8_desc: '그린 & 내추럴, 친환경 비즈니스에 적합',
    tpl9_name: 'Tech Startup', tpl9_desc: '모던한 SaaS 스타일, 테크 기업에 적합',
    tpl10_name: 'Freelance', tpl10_desc: '경쾌하고 개인적인 느낌, 프리랜서에 적합',
  },
  zh: {
    nav_templates: '模板', nav_create: '创建发票',
    hero_title: '100多种免费发票模板',
    hero_subtitle: '几分钟内创建专业发票。选择设计，填写信息，直接发送。',
    hero_cta: '立即创建发票！',
    gallery_title: '选择您的发票设计', gallery_subtitle: '从这里开始创建您的专业发票！',
    see_all: '查看所有模板',
    f1_title: '创建发票', f1_desc: '从众多模板中选择，添加您的公司标志。',
    f2_title: '通过电子邮件发送', f2_desc: '以PDF格式直接发送给客户，或打印。',
    f3_title: '接收付款', f3_desc: '在线更快地收到付款。',
    footer: '为小组作业制作 — InvoiceKita 2026',
    tp_title: '选择发票模板', tp_subtitle: '10种专业设计，免费使用。',
    use_template: '使用此模板 →',
    et_title: '创建发票', et_info: '基本信息', et_invoice_number: '发票号码', et_status: '状态',
    et_status_unpaid: '未付款', et_status_paid: '已付款', et_status_overdue: '逾期',
    et_issue_date: '开票日期', et_due_date: '到期日期',
    et_from: '发件人（您的公司）', et_to: '收件人（客户）',
    et_company_name: '公司名称', et_address: '地址', et_email: '邮箱', et_phone: '电话',
    et_client_name: '客户名称', et_items: '项目', et_add_item: '+ 添加项目',
    et_description: '描述', et_qty: '数量', et_price: '价格',
    et_tax: '税率 (%)', et_discount: '折扣 (%)', et_notes: '备注',
    tpl1_name: 'Neat Minimal', tpl1_desc: '简洁干净，适合现代企业',
    tpl2_name: 'Classic Corporate', tpl2_desc: '正式风格，适合大公司',
    tpl3_name: 'Bold Band', tpl3_desc: '鲜艳大胆的色彩，吸引眼球',
    tpl4_name: 'Modern Gradient', tpl4_desc: '色彩渐变，富有创意感',
    tpl5_name: 'Dark Studio', tpl5_desc: '深色主题，适合科技工作室',
    tpl6_name: 'Elegant Luxury', tpl6_desc: '金色优雅，高端质感',
    tpl7_name: 'Creative Asymmetric', tpl7_desc: '独特分割布局，适合创意机构',
    tpl8_name: 'Nature Eco', tpl8_desc: '绿色自然，适合环保企业',
    tpl9_name: 'Tech Startup', tpl9_desc: '现代SaaS风格，适合科技公司',
    tpl10_name: 'Freelance', tpl10_desc: '俏皮个性，适合自由职业者',
  },
};

const languageNames = {
  id: '🇮🇩 Indonesia', en: '🇬🇧 English', es: '🇪🇸 Español', fr: '🇫🇷 Français',
  de: '🇩🇪 Deutsch', it: '🇮🇹 Italiano', pt: '🇵🇹 Português', ja: '🇯🇵 日本語',
  ko: '🇰🇷 한국어', zh: '🇨🇳 中文',
};

function createLang() {
  let current = $state('id');

  return {
    get current() { return current; },
    get options() { return languageNames; },
    set(code) {
      current = code;
      localStorage.setItem('lang', code);
    },
    init() {
      const saved = localStorage.getItem('lang');
      if (saved && translations[saved]) current = saved;
    },
    t(key) {
      return translations[current]?.[key] ?? translations.en[key] ?? key;
    },
  };
}

export const lang = createLang();