const languageNames = {
  id: '🇮🇩 Indonesia',
  en: '🇬🇧 English',
  es: '🇪🇸 Español',
  fr: '🇫🇷 Français',
  de: '🇩🇪 Deutsch',
  it: '🇮🇹 Italiano',
  pt: '🇵🇹 Português',
  ja: '🇯🇵 日本語',
  ko: '🇰🇷 한국어',
  zh: '🇨🇳 中文'
};

const templateNames = {
  id: [
    'Neat Minimal',
    'Classic Corporate',
    'Bold Band',
    'Modern Gradient',
    'Dark Studio',
    'Elegant Luxury',
    'Creative Asymmetric',
    'Nature Eco',
    'Tech Startup',
    'Freelance',
    'Bold Typography',
    'Dark Tech',
    'Editorial Koran',
    'Gold Elegant',
    'Modern Minimalis',
    'Gradient Vibrant',
    'Classic Formal',
    'Minimalis',
    'Klasik Elegan',
    'Floral Playful',
    'Retro Vintage',
    'Neon Bright',
    'Curved Teal',
    'Pixel Receipt',
    'Ledger Klasik',
    'Swiss Grid',
    'Motif Warm',
    'Minimalis Mono',
    'Studio Hitam',
    'Brutalist Bracket',
    'Editorial Merah',
    'Sidebar Biru',
    'Editorial Merah',
    'Sidebar Biru',
    'Aurora Night',
    'Cream Monogramme',
    'Dotted Blue Wave',
    'Indigo Swirl',
    'Crimson VAT',
    'Pill Rows Indigo',
    'Signature Cream',
    'Lavender Soft',
    'Coral Gradient Bar',
    'Slate Corporate'
  ],

  en: [
    'Neat Minimal',
    'Classic Corporate',
    'Bold Band',
    'Modern Gradient',
    'Dark Studio',
    'Elegant Luxury',
    'Creative Asymmetric',
    'Nature Eco',
    'Tech Startup',
    'Freelance',
    'Bold Typography',
    'Dark Tech',
    'Editorial Newspaper',
    'Gold Elegant',
    'Modern Minimalist',
    'Gradient Vibrant',
    'Classic Formal',
    'Minimalist',
    'Classic Elegant',
    'Floral Playful',
    'Retro Vintage',
    'Neon Bright',
    'Curved Teal',
    'Pixel Receipt',
    'Classic Ledger',
    'Swiss Grid',
    'Warm Motif',
    'Minimal Mono',
    'Black Studio',
    'Brutalist Bracket',
    'Red Editorial',
    'Blue Sidebar'
  ],

  es: [
    'Minimalista Limpio',
    'Corporativo Clásico',
    'Banda Audaz',
    'Degradado Moderno',
    'Estudio Oscuro',
    'Lujo Elegante',
    'Asimétrico Creativo',
    'Naturaleza Ecológica',
    'Startup Tecnológica',
    'Freelance',
    'Tipografía Audaz',
    'Tecnología Oscura',
    'Periódico Editorial',
    'Elegante Dorado',
    'Minimalista Moderno',
    'Degradado Vibrante',
    'Formal Clásico',
    'Minimalista',
    'Clásico Elegante',
    'Floral Divertido',
    'Retro Vintage',
    'Neón Brillante',
    'Turquesa Curvo',
    'Recibo Pixel',
    'Libro Contable Clásico',
    'Cuadrícula Suiza',
    'Motivo Cálido',
    'Minimalista Monocromo',
    'Estudio Negro',
    'Corchete Brutalista',
    'Editorial Rojo',
    'Barra Lateral Azul'
  ],

  fr: [
    'Minimal Épuré',
    'Corporatif Classique',
    'Bande Audacieuse',
    'Dégradé Moderne',
    'Studio Sombre',
    'Luxe Élégant',
    'Asymétrique Créatif',
    'Nature Écologique',
    'Startup Technologique',
    'Freelance',
    'Typographie Audacieuse',
    'Tech Sombre',
    'Journal Éditorial',
    'Élégance Dorée',
    'Minimaliste Moderne',
    'Dégradé Vibrant',
    'Formel Classique',
    'Minimaliste',
    'Classique Élégant',
    'Floral Ludique',
    'Rétro Vintage',
    'Néon Éclatant',
    'Turquoise Courbé',
    'Reçu Pixel',
    'Grand Livre Classique',
    'Grille Suisse',
    'Motif Chaleureux',
    'Minimal Mono',
    'Studio Noir',
    'Crochet Brutaliste',
    'Éditorial Rouge',
    'Barre Latérale Bleue'
  ],

  de: [
    'Schlicht Minimal',
    'Klassisch Corporate',
    'Fettes Band',
    'Moderner Farbverlauf',
    'Dunkles Studio',
    'Eleganter Luxus',
    'Kreativ Asymmetrisch',
    'Natur Öko',
    'Tech Startup',
    'Freelance',
    'Fette Typografie',
    'Dunkle Technik',
    'Redaktionelle Zeitung',
    'Gold Elegant',
    'Modern Minimalistisch',
    'Lebendiger Farbverlauf',
    'Klassisch Formal',
    'Minimalistisch',
    'Klassisch Elegant',
    'Verspielt Floral',
    'Retro Vintage',
    'Neon Hell',
    'Gebogenes Türkis',
    'Pixel Quittung',
    'Klassisches Kontobuch',
    'Schweizer Raster',
    'Warmes Motiv',
    'Minimal Mono',
    'Schwarzes Studio',
    'Brutalistischer Rahmen',
    'Rote Redaktion',
    'Blaue Seitenleiste'
  ],

  it: [
    'Minimal Pulito',
    'Corporate Classico',
    'Banda Audace',
    'Gradiente Moderno',
    'Studio Scuro',
    'Lusso Elegante',
    'Asimmetrico Creativo',
    'Natura Eco',
    'Startup Tecnologica',
    'Freelance',
    'Tipografia Audace',
    'Tech Scuro',
    'Giornale Editoriale',
    'Elegante Dorato',
    'Minimal Moderno',
    'Gradiente Vivace',
    'Classico Formale',
    'Minimalista',
    'Classico Elegante',
    'Floreale Giocoso',
    'Retro Vintage',
    'Neon Brillante',
    'Turchese Curvo',
    'Ricevuta Pixel',
    'Registro Classico',
    'Griglia Svizzera',
    'Motivo Caldo',
    'Minimal Mono',
    'Studio Nero',
    'Cornice Brutalista',
    'Editoriale Rosso',
    'Barra Laterale Blu'
  ],

  pt: [
    'Minimalista Limpo',
    'Corporativo Clássico',
    'Faixa Ousada',
    'Gradiente Moderno',
    'Estúdio Escuro',
    'Luxo Elegante',
    'Assimétrico Criativo',
    'Natureza Eco',
    'Startup de Tecnologia',
    'Freelance',
    'Tipografia Ousada',
    'Tecnologia Escura',
    'Jornal Editorial',
    'Elegante Dourado',
    'Minimalista Moderno',
    'Gradiente Vibrante',
    'Formal Clássico',
    'Minimalista',
    'Clássico Elegante',
    'Floral Divertido',
    'Retro Vintage',
    'Neon Brilhante',
    'Turquesa Curvo',
    'Recibo Pixel',
    'Livro Contábil Clássico',
    'Grade Suíça',
    'Motivo Quente',
    'Minimal Mono',
    'Estúdio Preto',
    'Colchete Brutalista',
    'Editorial Vermelho',
    'Barra Lateral Azul'
  ],

  ja: [
    'シンプルミニマル',
    'クラシックコーポレート',
    'ボールドバンド',
    'モダングラデーション',
    'ダークスタジオ',
    'エレガントラグジュアリー',
    'クリエイティブ非対称',
    'ネイチャーエコ',
    'テックスタートアップ',
    'フリーランス',
    'ボールドタイポグラフィ',
    'ダークテック',
    'エディトリアル新聞',
    'ゴールドエレガント',
    'モダンミニマル',
    'グラデーションビブラント',
    'クラシックフォーマル',
    'ミニマリスト',
    'クラシックエレガント',
    'フローラルプレイフル',
    'レトロヴィンテージ',
    'ネオンブライト',
    'カーブドティール',
    'ピクセルレシート',
    'クラシック台帳',
    'スイスグリッド',
    'ウォームモチーフ',
    'ミニマルモノ',
    'ブラックスタジオ',
    'ブルータリストブラケット',
    'レッドエディトリアル',
    'ブルーサイドバー'
  ],

  ko: [
    '깔끔한 미니멀',
    '클래식 기업형',
    '볼드 밴드',
    '모던 그라디언트',
    '다크 스튜디오',
    '엘레강트 럭셔리',
    '크리에이티브 비대칭',
    '네이처 에코',
    '테크 스타트업',
    '프리랜서',
    '볼드 타이포그래피',
    '다크 테크',
    '에디토리얼 신문',
    '골드 엘레강트',
    '모던 미니멀리스트',
    '그라디언트 비브런트',
    '클래식 포멀',
    '미니멀리스트',
    '클래식 엘레강트',
    '플로럴 플레이풀',
    '레트로 빈티지',
    '네온 브라이트',
    '커브드 틸',
    '픽셀 영수증',
    '클래식 원장',
    '스위스 그리드',
    '웜 모티프',
    '미니멀 모노',
    '블랙 스튜디오',
    '브루탈리스트 브래킷',
    '레드 에디토리얼',
    '블루 사이드바'
  ],

  zh: [
    '简约整洁',
    '经典企业',
    '大胆色带',
    '现代渐变',
    '暗黑工作室',
    '优雅奢华',
    '创意不对称',
    '自然环保',
    '科技创业',
    '自由职业',
    '大胆字体',
    '暗黑科技',
    '报纸编辑风',
    '金色优雅',
    '现代极简',
    '活力渐变',
    '经典正式',
    '极简主义',
    '经典优雅',
    '花卉趣味',
    '复古怀旧',
    '霓虹明亮',
    '弧形青绿色',
    '像素收据',
    '经典账本',
    '瑞士网格',
    '温暖图案',
    '极简单色',
    '黑色工作室',
    '野兽派括号',
    '红色编辑风',
    '蓝色侧边栏'
  ]
};

const ui = {
  id: {
    nav_templates: 'Template',
    nav_create: 'Buat Invoice',

    hero_title: '25+ Template Invoice Gratis',
    hero_subtitle: 'Buat invoice profesional dalam hitungan menit. Pilih desain, isi data, langsung kirim.',
    hero_cta: 'Buat Invoice Sekarang!',
    gallery_title: 'Pilih Desain Invoice Kamu',
    gallery_subtitle: 'Mulai membuat invoice profesional dari sini!',
    see_all: 'Lihat Semua Template',

    f1_title: 'Buat Invoice',
    f1_desc: 'Pilih dari banyak template, tambahkan logo perusahaanmu.',
    f2_title: 'Kirim via Email',
    f2_desc: 'Kirim sebagai PDF langsung ke klien, atau cetak.',
    f3_title: 'Terima Pembayaran',
    f3_desc: 'Dapatkan pembayaran lebih cepat secara online.',

    footer: 'Dibuat untuk tugas kelompok — InvoiceKita 2026',

    tp_title: 'Pilih Template Invoice',
    tp_subtitle: '25+ desain profesional, gratis untuk dipakai.',
    use_template: 'Gunakan template →',

    et_title: 'Buat Invoice',
    et_info: 'Info Dasar',
    et_invoice_number: 'No. Invoice',
    et_status: 'Status',
    et_status_unpaid: 'Belum Dibayar',
    et_status_paid: 'Lunas',
    et_status_overdue: 'Terlambat',
    et_issue_date: 'Tanggal Terbit',
    et_due_date: 'Jatuh Tempo',
    et_from: 'Dari (Perusahaan Kamu)',
    et_to: 'Kepada (Klien)',
    et_company_name: 'Nama perusahaan',
    et_address: 'Alamat',
    et_email: 'Email',
    et_phone: 'Telepon',
    et_client_name: 'Nama klien',
    et_items: 'Item',
    et_add_item: '+ Tambah Item',
    et_description: 'Deskripsi',
    et_qty: 'Qty',
    et_price: 'Harga',
    et_tax: 'Pajak (%)',
    et_discount: 'Diskon (%)',
    et_notes: 'Catatan',

    logo_company: 'Logo Perusahaan',
    logo_empty: 'Belum ada logo',
    logo_remove: 'Hapus logo',
    logo_file_error: 'File harus berupa gambar (PNG/JPG/SVG).',
    logo_size_error: 'Ukuran gambar maksimal 2MB.',

    save_invoice: '💾 Simpan Invoice',
    saving_invoice: 'Menyimpan...',
    download_pdf: '📄 Download PDF',
    generating_pdf: 'Membuat PDF...',
    logout: 'Logout',
    save_success: 'Invoice berhasil disimpan!',
    save_failed: 'Gagal menyimpan',

    tpl1_name: 'Neat Minimal', tpl1_desc: 'Simpel & bersih, cocok untuk bisnis modern',
    tpl2_name: 'Classic Corporate', tpl2_desc: 'Formal, cocok untuk perusahaan besar',
    tpl3_name: 'Bold Band', tpl3_desc: 'Warna cerah & berani, menarik perhatian',
    tpl4_name: 'Modern Gradient', tpl4_desc: 'Gradasi warna, kesan kreatif & fresh',
    tpl5_name: 'Dark Studio', tpl5_desc: 'Tema gelap, cocok untuk studio digital/tech',
    tpl6_name: 'Elegant Luxury', tpl6_desc: 'Emas & elegan, kesan premium',
    tpl7_name: 'Creative Asymmetric', tpl7_desc: 'Layout split unik, cocok untuk agensi kreatif',
    tpl8_name: 'Nature Eco', tpl8_desc: 'Hijau & natural, untuk bisnis ramah lingkungan',
    tpl9_name: 'Tech Startup', tpl9_desc: 'Gaya SaaS modern, untuk perusahaan teknologi',
    tpl10_name: 'Freelance', tpl10_desc: 'Playful & personal, cocok untuk freelancer',
    tpl11_name: 'Bold Typography', tpl11_desc: 'Tipografi besar dan tegas, gaya editorial modern',
    tpl12_name: 'Dark Tech', tpl12_desc: 'Tema gelap ala perusahaan teknologi',
    tpl13_name: 'Editorial Koran', tpl13_desc: 'Gaya kolom koran/majalah, formal dan rapi',
    tpl14_name: 'Elegan Emas', tpl14_desc: 'Aksen emas mewah, kesan premium',
    tpl15_name: 'Gradient Vibrant', tpl15_desc: 'Gradasi warna cerah dan hidup',
    tpl16_name: 'Klasik Formal', tpl16_desc: 'Tampilan klasik yang resmi dan profesional',
    tpl17_name: 'Korporat Biru', tpl17_desc: 'Biru korporat, cocok untuk perusahaan besar',
    tpl18_name: 'Modern Minimalis', tpl18_desc: 'Minimalis modern dengan ruang kosong yang lega',
    tpl19_name: 'Nordic Earthy', tpl19_desc: 'Palet warna earthy ala desain Skandinavia',
    tpl20_name: 'Pastel Playful', tpl20_desc: 'Warna pastel ceria dan playful',
    tpl21_name: 'Retro Vintage', tpl21_desc: 'Nuansa retro klasik era vintage',
    tpl22_name: 'Tech SaaS', tpl22_desc: 'Gaya SaaS modern untuk produk teknologi',
    tpl23_name: 'Curved Teal', tpl23_desc: 'Header melengkung, gaya hangat',
    tpl24_name: 'Pixel Receipt', tpl24_desc: 'Struk monospace, tepi bergerigi',
    tpl25_name: 'Ledger Klasik', tpl25_desc: 'Gaya buku kas akuntansi lama',
    tpl26_name: 'Swiss Grid', tpl26_desc: 'Grid tegas ala desain Swiss',
    tpl27_name: 'Motif Warm', tpl27_desc: 'Indigo & emas, kesan mewah',
    tpl28_name: 'Minimalis Mono', tpl28_desc: 'Nyaris tanpa warna, fokus tipografi',
    tpl29_name: 'Studio Hitam', tpl29_desc: 'Hitam pekat, garis putih tegas',
    tpl30_name: 'Brutalist Bracket', tpl30_desc: 'Flat & tegas, gaya brutalist',
    tpl31_name: 'Editorial Merah', tpl31_desc: 'Headline merah besar ala majalah',
    tpl32_name: 'Sidebar Biru', tpl32_desc: 'Sidebar biru solid untuk identitas',
    tpl33_name: 'Aurora Night', tpl33_desc: 'Banner gradasi biru-oranye, gaya studio digital',
    tpl34_name: 'Cream Monogramme', tpl34_desc: 'Krem elegan dengan tipografi serif',
    tpl35_name: 'Dotted Blue Wave', tpl35_desc: 'Header biru melengkung dengan pola titik',
    tpl36_name: 'Indigo Swirl', tpl36_desc: 'Logo swirl ungu, tabel header solid',
    tpl37_name: 'Crimson VAT', tpl37_desc: 'Merah solid, gaya invoice VAT Eropa',
    tpl38_name: 'Pill Rows Indigo', tpl38_desc: 'Baris item berbentuk kapsul/pill',
    tpl39_name: 'Signature Cream', tpl39_desc: 'Monogram elegan dengan tanda tangan',
    tpl40_name: 'Lavender Soft', tpl40_desc: 'Pastel ungu lembut, kartu rounded',
    tpl41_name: 'Coral Gradient Bar', tpl41_desc: 'Pita gradasi coral-pink di header',
    tpl42_name: 'Slate Corporate', tpl42_desc: 'Abu kebiruan formal dan bersih',

  },

  en: {
    nav_templates: 'Templates',
    nav_create: 'Create Invoice',

    hero_title: '25+ Free Invoice Templates',
    hero_subtitle: 'Create a professional invoice in minutes. Pick a design, fill in the details, send it.',
    hero_cta: 'Create Invoice Now!',
    gallery_title: 'Choose Your Invoice Design',
    gallery_subtitle: 'Start creating your professional invoice here!',
    see_all: 'See All Templates',

    f1_title: 'Create an Invoice',
    f1_desc: 'Choose from many templates and add your company logo.',
    f2_title: 'Send via Email',
    f2_desc: 'Send as a PDF directly to your client, or print it.',
    f3_title: 'Get Paid',
    f3_desc: 'Receive payments faster online.',

    footer: 'Made for a group project — InvoiceKita 2026',

    tp_title: 'Choose an Invoice Template',
    tp_subtitle: '25+ professional designs, free to use.',
    use_template: 'Use this template →',

    et_title: 'Create Invoice',
    et_info: 'Basic Info',
    et_invoice_number: 'Invoice No.',
    et_status: 'Status',
    et_status_unpaid: 'Unpaid',
    et_status_paid: 'Paid',
    et_status_overdue: 'Overdue',
    et_issue_date: 'Issue Date',
    et_due_date: 'Due Date',
    et_from: 'From (Your Company)',
    et_to: 'To (Client)',
    et_company_name: 'Company name',
    et_address: 'Address',
    et_email: 'Email',
    et_phone: 'Phone',
    et_client_name: 'Client name',
    et_items: 'Items',
    et_add_item: '+ Add Item',
    et_description: 'Description',
    et_qty: 'Qty',
    et_price: 'Price',
    et_tax: 'Tax (%)',
    et_discount: 'Discount (%)',
    et_notes: 'Notes',

    logo_company: 'Company Logo',
    logo_empty: 'No logo yet',
    logo_remove: 'Remove logo',
    logo_file_error: 'File must be an image (PNG/JPG/SVG).',
    logo_size_error: 'Maximum image size is 2MB.',

    save_invoice: '💾 Save Invoice',
    saving_invoice: 'Saving...',
    download_pdf: '📄 Download PDF',
    generating_pdf: 'Creating PDF...',
    logout: 'Logout',
    save_success: 'Invoice saved successfully!',
    save_failed: 'Failed to save',
        tpl1_name: 'Neat Minimal', tpl1_desc: 'Simple & clean, for modern business',
    tpl2_name: 'Classic Corporate', tpl2_desc: 'Formal, for large companies',
    tpl3_name: 'Bold Band', tpl3_desc: 'Bright & bold colors, eye-catching',
    tpl4_name: 'Modern Gradient', tpl4_desc: 'Color gradients, creative & fresh feel',
    tpl5_name: 'Dark Studio', tpl5_desc: 'Dark theme, for digital/tech studios',
    tpl6_name: 'Elegant Luxury', tpl6_desc: 'Gold & elegant, premium feel',
    tpl7_name: 'Creative Asymmetric', tpl7_desc: 'Unique split layout, for creative agencies',
    tpl8_name: 'Nature Eco', tpl8_desc: 'Green & natural, for eco-friendly businesses',
    tpl9_name: 'Tech Startup', tpl9_desc: 'Modern SaaS style, for tech companies',
    tpl10_name: 'Freelance', tpl10_desc: 'Playful & personal, for freelancers',
    tpl11_name: 'Bold Typography', tpl11_desc: 'Big bold typography, modern editorial style',
    tpl12_name: 'Dark Tech', tpl12_desc: 'Dark theme for tech companies',
    tpl13_name: 'Editorial Koran', tpl13_desc: 'Newspaper/magazine column style, formal and neat',
    tpl14_name: 'Elegan Emas', tpl14_desc: 'Luxurious gold accents, premium feel',
    tpl15_name: 'Gradient Vibrant', tpl15_desc: 'Bright and lively color gradients',
    tpl16_name: 'Klasik Formal', tpl16_desc: 'Classic, official and professional look',
    tpl17_name: 'Korporat Biru', tpl17_desc: 'Corporate blue, for large companies',
    tpl18_name: 'Modern Minimalis', tpl18_desc: 'Modern minimalism with generous white space',
    tpl19_name: 'Nordic Earthy', tpl19_desc: 'Earthy color palette, Scandinavian design',
    tpl20_name: 'Pastel Playful', tpl20_desc: 'Cheerful and playful pastel colors',
    tpl21_name: 'Retro Vintage', tpl21_desc: 'Classic retro, vintage era feel',
    tpl22_name: 'Tech SaaS', tpl22_desc: 'Modern SaaS style for tech products',
    tpl23_name: 'Curved Teal', tpl23_desc: 'Curved header, warm feel',
    tpl24_name: 'Pixel Receipt', tpl24_desc: 'Monospace receipt, jagged edges',
    tpl25_name: 'Ledger Klasik', tpl25_desc: 'Old-school accounting ledger style',
    tpl26_name: 'Swiss Grid', tpl26_desc: 'Bold grid, Swiss design style',
    tpl27_name: 'Motif Warm', tpl27_desc: 'Indigo & gold, luxurious feel',
    tpl28_name: 'Minimalis Mono', tpl28_desc: 'Nearly colorless, typography-focused',
    tpl29_name: 'Studio Hitam', tpl29_desc: 'Deep black, bold white lines',
    tpl30_name: 'Brutalist Bracket', tpl30_desc: 'Flat and bold, brutalist style',
    tpl31_name: 'Editorial Merah', tpl31_desc: 'Big red headline, magazine style',
    tpl32_name: 'Sidebar Biru', tpl32_desc: 'Solid blue sidebar for identity',
    tpl33_name: 'Aurora Night', tpl33_desc: 'Blue-orange gradient banner, digital studio style',
    tpl34_name: 'Cream Monogramme', tpl34_desc: 'Elegant cream with serif typography',
    tpl35_name: 'Dotted Blue Wave', tpl35_desc: 'Curved blue header with dot pattern',
    tpl36_name: 'Indigo Swirl', tpl36_desc: 'Purple swirl logo, solid table header',
    tpl37_name: 'Crimson VAT', tpl37_desc: 'Solid red, European VAT invoice style',
    tpl38_name: 'Pill Rows Indigo', tpl38_desc: 'Capsule/pill-shaped item rows',
    tpl39_name: 'Signature Cream', tpl39_desc: 'Elegant monogram with signature',
    tpl40_name: 'Lavender Soft', tpl40_desc: 'Soft purple pastel, rounded cards',
    tpl41_name: 'Coral Gradient Bar', tpl41_desc: 'Coral-pink gradient header bar',
    tpl42_name: 'Slate Corporate', tpl42_desc: 'Formal, clean slate blue',

  },

  es: {
    nav_templates: 'Plantillas',
    nav_create: 'Crear Factura',
    hero_title: '25+ Plantillas de Factura Gratis',
    hero_subtitle: 'Crea una factura profesional en minutos. Elige un diseño, completa los datos, envíala.',
    hero_cta: '¡Crear Factura Ahora!',
    gallery_title: 'Elige tu Diseño de Factura',
    gallery_subtitle: '¡Empieza a crear tu factura profesional aquí!',
    see_all: 'Ver Todas las Plantillas',
    f1_title: 'Crea una Factura',
    f1_desc: 'Elige entre varias plantillas y añade el logo de tu empresa.',
    f2_title: 'Envía por Email',
    f2_desc: 'Envía como PDF directamente a tu cliente, o imprímela.',
    f3_title: 'Recibe Pagos',
    f3_desc: 'Recibe pagos más rápido en línea.',
    footer: 'Hecho para un proyecto grupal — InvoiceKita 2026',
    tp_title: 'Elige una Plantilla de Factura',
    tp_subtitle: '25+ diseños profesionales, gratis para usar.',
    use_template: 'Usar esta plantilla →',

    et_title: 'Crear Factura',
    et_info: 'Información Básica',
    et_invoice_number: 'N.º de Factura',
    et_status: 'Estado',
    et_status_unpaid: 'Sin Pagar',
    et_status_paid: 'Pagada',
    et_status_overdue: 'Vencida',
    et_issue_date: 'Fecha de Emisión',
    et_due_date: 'Fecha de Vencimiento',
    et_from: 'De (Tu Empresa)',
    et_to: 'Para (Cliente)',
    et_company_name: 'Nombre de la empresa',
    et_address: 'Dirección',
    et_email: 'Email',
    et_phone: 'Teléfono',
    et_client_name: 'Nombre del cliente',
    et_items: 'Artículos',
    et_add_item: '+ Añadir Artículo',
    et_description: 'Descripción',
    et_qty: 'Cant.',
    et_price: 'Precio',
    et_tax: 'Impuesto (%)',
    et_discount: 'Descuento (%)',
    et_notes: 'Notas',

    logo_company: 'Logo de la Empresa',
    logo_empty: 'No hay logo',
    logo_remove: 'Eliminar logo',
    logo_file_error: 'El archivo debe ser una imagen (PNG/JPG/SVG).',
    logo_size_error: 'El tamaño máximo es 2MB.',

    save_invoice: '💾 Guardar Factura',
    saving_invoice: 'Guardando...',
    download_pdf: '📄 Descargar PDF',
    generating_pdf: 'Creando PDF...',
    logout: 'Cerrar Sesión',
    save_success: '¡Factura guardada correctamente!',
    save_failed: 'Error al guardar'
  },

  fr: {
    nav_templates: 'Modèles',
    nav_create: 'Créer une Facture',
    hero_title: '25+ Modèles de Facture Gratuits',
    hero_subtitle: 'Créez une facture professionnelle en quelques minutes. Choisissez un modèle, remplissez les détails, envoyez-la.',
    hero_cta: 'Créer une Facture Maintenant !',
    gallery_title: 'Choisissez votre Modèle de Facture',
    gallery_subtitle: 'Commencez à créer votre facture professionnelle ici !',
    see_all: 'Voir Tous les Modèles',
    f1_title: 'Créer une Facture',
    f1_desc: 'Choisissez parmi de nombreux modèles et ajoutez le logo de votre entreprise.',
    f2_title: 'Envoyer par Email',
    f2_desc: 'Envoyez en PDF directement à votre client, ou imprimez-la.',
    f3_title: 'Soyez Payé',
    f3_desc: 'Recevez des paiements plus rapidement en ligne.',
    footer: 'Réalisé pour un projet de groupe — InvoiceKita 2026',
    tp_title: 'Choisissez un Modèle de Facture',
    tp_subtitle: '25+ designs professionnels, gratuits à utiliser.',
    use_template: 'Utiliser ce modèle →',

    et_title: 'Créer une Facture',
    et_info: 'Infos de Base',
    et_invoice_number: 'N° de Facture',
    et_status: 'Statut',
    et_status_unpaid: 'Non Payée',
    et_status_paid: 'Payée',
    et_status_overdue: 'En Retard',
    et_issue_date: "Date d'Émission",
    et_due_date: "Date d'Échéance",
    et_from: 'De (Votre Entreprise)',
    et_to: 'À (Client)',
    et_company_name: "Nom de l'entreprise",
    et_address: 'Adresse',
    et_email: 'Email',
    et_phone: 'Téléphone',
    et_client_name: 'Nom du client',
    et_items: 'Articles',
    et_add_item: '+ Ajouter un Article',
    et_description: 'Description',
    et_qty: 'Qté',
    et_price: 'Prix',
    et_tax: 'Taxe (%)',
    et_discount: 'Remise (%)',
    et_notes: 'Notes',

    logo_company: 'Logo de l’Entreprise',
    logo_empty: 'Aucun logo',
    logo_remove: 'Supprimer le logo',
    logo_file_error: 'Le fichier doit être une image (PNG/JPG/SVG).',
    logo_size_error: 'La taille maximale est de 2 Mo.',

    save_invoice: '💾 Enregistrer la Facture',
    saving_invoice: 'Enregistrement...',
    download_pdf: '📄 Télécharger le PDF',
    generating_pdf: 'Création du PDF...',
    logout: 'Déconnexion',
    save_success: 'Facture enregistrée avec succès !',
    save_failed: 'Échec de l’enregistrement'
  },

  de: {
    nav_templates: 'Vorlagen',
    nav_create: 'Rechnung Erstellen',
    hero_title: '25+ Kostenlose Rechnungsvorlagen',
    hero_subtitle: 'Erstellen Sie in wenigen Minuten eine professionelle Rechnung. Design wählen, Daten eingeben, senden.',
    hero_cta: 'Jetzt Rechnung Erstellen!',
    gallery_title: 'Wählen Sie Ihr Rechnungsdesign',
    gallery_subtitle: 'Beginnen Sie hier mit der Erstellung Ihrer professionellen Rechnung!',
    see_all: 'Alle Vorlagen Ansehen',
    f1_title: 'Rechnung Erstellen',
    f1_desc: 'Wählen Sie aus vielen Vorlagen und fügen Sie Ihr Firmenlogo hinzu.',
    f2_title: 'Per E-Mail Senden',
    f2_desc: 'Senden Sie als PDF direkt an Ihren Kunden oder drucken Sie sie aus.',
    f3_title: 'Bezahlt Werden',
    f3_desc: 'Erhalten Sie Zahlungen schneller online.',
    footer: 'Erstellt für ein Gruppenprojekt — InvoiceKita 2026',
    tp_title: 'Wählen Sie eine Rechnungsvorlage',
    tp_subtitle: '25+ professionelle Designs, kostenlos nutzbar.',
    use_template: 'Vorlage verwenden →',

    et_title: 'Rechnung Erstellen',
    et_info: 'Grundinfos',
    et_invoice_number: 'Rechnungsnr.',
    et_status: 'Status',
    et_status_unpaid: 'Unbezahlt',
    et_status_paid: 'Bezahlt',
    et_status_overdue: 'Überfällig',
    et_issue_date: 'Ausstellungsdatum',
    et_due_date: 'Fälligkeitsdatum',
    et_from: 'Von (Ihr Unternehmen)',
    et_to: 'An (Kunde)',
    et_company_name: 'Firmenname',
    et_address: 'Adresse',
    et_email: 'E-Mail',
    et_phone: 'Telefon',
    et_client_name: 'Kundenname',
    et_items: 'Artikel',
    et_add_item: '+ Artikel Hinzufügen',
    et_description: 'Beschreibung',
    et_qty: 'Menge',
    et_price: 'Preis',
    et_tax: 'Steuer (%)',
    et_discount: 'Rabatt (%)',
    et_notes: 'Notizen',

    logo_company: 'Firmenlogo',
    logo_empty: 'Noch kein Logo',
    logo_remove: 'Logo entfernen',
    logo_file_error: 'Die Datei muss ein Bild sein (PNG/JPG/SVG).',
    logo_size_error: 'Die maximale Bildgröße beträgt 2 MB.',

    save_invoice: '💾 Rechnung Speichern',
    saving_invoice: 'Speichern...',
    download_pdf: '📄 PDF Herunterladen',
    generating_pdf: 'PDF wird erstellt...',
    logout: 'Abmelden',
    save_success: 'Rechnung erfolgreich gespeichert!',
    save_failed: 'Speichern fehlgeschlagen'
  },

  it: {
    nav_templates: 'Modelli',
    nav_create: 'Crea Fattura',
    hero_title: '25+ Modelli di Fattura Gratuiti',
    hero_subtitle: 'Crea una fattura professionale in pochi minuti. Scegli un design, inserisci i dati, invia.',
    hero_cta: 'Crea Fattura Ora!',
    gallery_title: 'Scegli il tuo Design della Fattura',
    gallery_subtitle: 'Inizia a creare la tua fattura professionale qui!',
    see_all: 'Vedi Tutti i Modelli',
    f1_title: 'Crea una Fattura',
    f1_desc: 'Scegli tra molti modelli e aggiungi il logo della tua azienda.',
    f2_title: 'Invia via Email',
    f2_desc: 'Invia come PDF direttamente al cliente, o stampala.',
    f3_title: 'Ricevi Pagamenti',
    f3_desc: 'Ricevi pagamenti più velocemente online.',
    footer: 'Realizzato per un progetto di gruppo — InvoiceKita 2026',
    tp_title: 'Scegli un Modello di Fattura',
    tp_subtitle: '25 design professionali, gratuiti da usare.',
    use_template: 'Usa questo modello →',

    et_title: 'Crea Fattura',
    et_info: 'Info di Base',
    et_invoice_number: 'N. Fattura',
    et_status: 'Stato',
    et_status_unpaid: 'Non Pagata',
    et_status_paid: 'Pagata',
    et_status_overdue: 'Scaduta',
    et_issue_date: 'Data di Emissione',
    et_due_date: 'Data di Scadenza',
    et_from: 'Da (La Tua Azienda)',
    et_to: 'A (Cliente)',
    et_company_name: 'Nome azienda',
    et_address: 'Indirizzo',
    et_email: 'Email',
    et_phone: 'Telefono',
    et_client_name: 'Nome cliente',
    et_items: 'Articoli',
    et_add_item: '+ Aggiungi Articolo',
    et_description: 'Descrizione',
    et_qty: 'Qtà',
    et_price: 'Prezzo',
    et_tax: 'Tassa (%)',
    et_discount: 'Sconto (%)',
    et_notes: 'Note',

    logo_company: 'Logo Aziendale',
    logo_empty: 'Nessun logo',
    logo_remove: 'Rimuovi logo',
    logo_file_error: 'Il file deve essere un’immagine (PNG/JPG/SVG).',
    logo_size_error: 'La dimensione massima è 2 MB.',

    save_invoice: '💾 Salva Fattura',
    saving_invoice: 'Salvataggio...',
    download_pdf: '📄 Scarica PDF',
    generating_pdf: 'Creazione PDF...',
    logout: 'Disconnetti',
    save_success: 'Fattura salvata con successo!',
    save_failed: 'Salvataggio non riuscito'
  },

  pt: {
    nav_templates: 'Modelos',
    nav_create: 'Criar Fatura',
    hero_title: '25+ Modelos de Fatura Grátis',
    hero_subtitle: 'Crie uma fatura profissional em minutos. Escolha um design, preencha os dados, envie.',
    hero_cta: 'Criar Fatura Agora!',
    gallery_title: 'Escolha o Design da sua Fatura',
    gallery_subtitle: 'Comece a criar sua fatura profissional aqui!',
    see_all: 'Ver Todos os Modelos',
    f1_title: 'Crie uma Fatura',
    f1_desc: 'Escolha entre vários modelos e adicione o logotipo da sua empresa.',
    f2_title: 'Envie por Email',
    f2_desc: 'Envie como PDF diretamente para o cliente, ou imprima.',
    f3_title: 'Receba Pagamentos',
    f3_desc: 'Receba pagamentos mais rápido online.',
    footer: 'Feito para um projeto em grupo — InvoiceKita 2026',
    tp_title: 'Escolha um Modelo de Fatura',
    tp_subtitle: '25 designs profissionais, grátis para usar.',
    use_template: 'Usar este modelo →',

    et_title: 'Criar Fatura',
    et_info: 'Informações Básicas',
    et_invoice_number: 'N.º da Fatura',
    et_status: 'Status',
    et_status_unpaid: 'Não Paga',
    et_status_paid: 'Paga',
    et_status_overdue: 'Atrasada',
    et_issue_date: 'Data de Emissão',
    et_due_date: 'Data de Vencimento',
    et_from: 'De (Sua Empresa)',
    et_to: 'Para (Cliente)',
    et_company_name: 'Nome da empresa',
    et_address: 'Endereço',
    et_email: 'Email',
    et_phone: 'Telefone',
    et_client_name: 'Nome do cliente',
    et_items: 'Itens',
    et_add_item: '+ Adicionar Item',
    et_description: 'Descrição',
    et_qty: 'Qtd',
    et_price: 'Preço',
    et_tax: 'Imposto (%)',
    et_discount: 'Desconto (%)',
    et_notes: 'Notas',

    logo_company: 'Logotipo da Empresa',
    logo_empty: 'Nenhum logotipo',
    logo_remove: 'Remover logotipo',
    logo_file_error: 'O arquivo deve ser uma imagem (PNG/JPG/SVG).',
    logo_size_error: 'O tamanho máximo é 2 MB.',

    save_invoice: '💾 Salvar Fatura',
    saving_invoice: 'Salvando...',
    download_pdf: '📄 Baixar PDF',
    generating_pdf: 'Criando PDF...',
    logout: 'Sair',
    save_success: 'Fatura salva com sucesso!',
    save_failed: 'Falha ao salvar'
  },

  ja: {
    nav_templates: 'テンプレート',
    nav_create: '請求書を作成',
    hero_title: '25+種類以上の無料請求書テンプレート',
    hero_subtitle: '数分でプロ仕様の請求書を作成。デザインを選んで、情報を入力し、送信するだけ。',
    hero_cta: '今すぐ請求書を作成！',
    gallery_title: '請求書デザインを選択',
    gallery_subtitle: 'ここからプロの請求書作成を始めましょう！',
    see_all: 'すべてのテンプレートを見る',
    f1_title: '請求書を作成',
    f1_desc: '多数のテンプレートから選び、会社のロゴを追加。',
    f2_title: 'メールで送信',
    f2_desc: 'PDFとしてクライアントに直接送信、または印刷。',
    f3_title: '支払いを受け取る',
    f3_desc: 'オンラインでより早く支払いを受け取れます。',
    footer: 'グループプロジェクトのために作成 — InvoiceKita 2026',
    tp_title: '請求書テンプレートを選択',
    tp_subtitle: '25+種類のプロデザイン、無料でご利用可能。',
    use_template: 'このテンプレートを使う →',

    et_title: '請求書を作成',
    et_info: '基本情報',
    et_invoice_number: '請求書番号',
    et_status: 'ステータス',
    et_status_unpaid: '未払い',
    et_status_paid: '支払済み',
    et_status_overdue: '延滞',
    et_issue_date: '発行日',
    et_due_date: '支払期限',
    et_from: '差出人（あなたの会社）',
    et_to: '宛先（クライアント）',
    et_company_name: '会社名',
    et_address: '住所',
    et_email: 'メール',
    et_phone: '電話番号',
    et_client_name: 'クライアント名',
    et_items: '項目',
    et_add_item: '+ 項目を追加',
    et_description: '説明',
    et_qty: '数量',
    et_price: '価格',
    et_tax: '税金 (%)',
    et_discount: '割引 (%)',
    et_notes: 'メモ',

    logo_company: '会社ロゴ',
    logo_empty: 'ロゴはまだありません',
    logo_remove: 'ロゴを削除',
    logo_file_error: '画像ファイルを選択してください（PNG/JPG/SVG）。',
    logo_size_error: '画像サイズは最大2MBです。',

    save_invoice: '💾 請求書を保存',
    saving_invoice: '保存中...',
    download_pdf: '📄 PDFをダウンロード',
    generating_pdf: 'PDFを作成中...',
    logout: 'ログアウト',
    save_success: '請求書を保存しました！',
    save_failed: '保存に失敗しました'
  },

  ko: {
    nav_templates: '템플릿',
    nav_create: '인보이스 만들기',
    hero_title: '25+ 개 이상의 무료 인보이스 템플릿',
    hero_subtitle: '몇 분 만에 전문적인 인보이스를 만드세요. 디자인을 선택하고, 정보를 입력하고, 바로 보내세요.',
    hero_cta: '지금 인보이스 만들기!',
    gallery_title: '인보이스 디자인 선택하기',
    gallery_subtitle: '여기서 전문적인 인보이스 만들기를 시작하세요!',
    see_all: '모든 템플릿 보기',
    f1_title: '인보이스 만들기',
    f1_desc: '다양한 템플릿 중에서 선택하고 회사 로고를 추가하세요.',
    f2_title: '이메일로 보내기',
    f2_desc: 'PDF로 클라이언트에게 바로 보내거나 인쇄하세요.',
    f3_title: '결제 받기',
    f3_desc: '온라인으로 더 빠르게 결제를 받으세요.',
    footer: '그룹 프로젝트를 위해 제작 — InvoiceKita 2026',
    tp_title: '인보이스 템플릿 선택',
    tp_subtitle: '25+ 가지 전문 디자인, 무료로 사용 가능.',
    use_template: '이 템플릿 사용하기 →',

    et_title: '인보이스 만들기',
    et_info: '기본 정보',
    et_invoice_number: '인보이스 번호',
    et_status: '상태',
    et_status_unpaid: '미결제',
    et_status_paid: '결제완료',
    et_status_overdue: '연체',
    et_issue_date: '발행일',
    et_due_date: '만기일',
    et_from: '보내는 사람 (귀사)',
    et_to: '받는 사람 (클라이언트)',
    et_company_name: '회사명',
    et_address: '주소',
    et_email: '이메일',
    et_phone: '전화번호',
    et_client_name: '클라이언트명',
    et_items: '항목',
    et_add_item: '+ 항목 추가',
    et_description: '설명',
    et_qty: '수량',
    et_price: '가격',
    et_tax: '세금 (%)',
    et_discount: '할인 (%)',
    et_notes: '메모',

    logo_company: '회사 로고',
    logo_empty: '아직 로고가 없습니다',
    logo_remove: '로고 삭제',
    logo_file_error: '이미지 파일이어야 합니다 (PNG/JPG/SVG).',
    logo_size_error: '이미지 최대 크기는 2MB입니다.',

    save_invoice: '💾 인보이스 저장',
    saving_invoice: '저장 중...',
    download_pdf: '📄 PDF 다운로드',
    generating_pdf: 'PDF 생성 중...',
    logout: '로그아웃',
    save_success: '인보이스가 저장되었습니다!',
    save_failed: '저장 실패'
  },

  zh: {
    nav_templates: '模板',
    nav_create: '创建发票',
    hero_title: '25+种免费发票模板',
    hero_subtitle: '几分钟内创建专业发票。选择设计，填写信息，直接发送。',
    hero_cta: '立即创建发票！',
    gallery_title: '选择您的发票设计',
    gallery_subtitle: '从这里开始创建您的专业发票！',
    see_all: '查看所有模板',
    f1_title: '创建发票',
    f1_desc: '从众多模板中选择，添加您的公司标志。',
    f2_title: '通过电子邮件发送',
    f2_desc: '以PDF格式直接发送给客户，或打印。',
    f3_title: '接收付款',
    f3_desc: '在线更快地收到付款。',
    footer: '为小组作业制作 — InvoiceKita 2026',
    tp_title: '选择发票模板',
    tp_subtitle: '25+种专业设计，免费使用。',
    use_template: '使用此模板 →',

    et_title: '创建发票',
    et_info: '基本信息',
    et_invoice_number: '发票号码',
    et_status: '状态',
    et_status_unpaid: '未付款',
    et_status_paid: '已付款',
    et_status_overdue: '逾期',
    et_issue_date: '开票日期',
    et_due_date: '到期日期',
    et_from: '发件人（您的公司）',
    et_to: '收件人（客户）',
    et_company_name: '公司名称',
    et_address: '地址',
    et_email: '邮箱',
    et_phone: '电话',
    et_client_name: '客户名称',
    et_items: '项目',
    et_add_item: '+ 添加项目',
    et_description: '描述',
    et_qty: '数量',
    et_price: '价格',
    et_tax: '税率 (%)',
    et_discount: '折扣 (%)',
    et_notes: '备注',

    logo_company: '公司标志',
    logo_empty: '暂无标志',
    logo_remove: '删除标志',
    logo_file_error: '文件必须是图片（PNG/JPG/SVG）。',
    logo_size_error: '图片最大尺寸为2MB。',

    save_invoice: '💾 保存发票',
    saving_invoice: '保存中...',
    download_pdf: '📄 下载PDF',
    generating_pdf: '正在创建PDF...',
    logout: '退出登录',
    save_success: '发票保存成功！',
    save_failed: '保存失败'
  }
};

function createLang() {
  let current = $state('id');

  return {
    get current() {
      return current;
    },

    get options() {
      return languageNames;
    },

    set(code) {
      if (!languageNames[code]) return;

      current = code;
      localStorage.setItem('lang', code);
    },

    init() {
      const saved = localStorage.getItem('lang');

      if (saved && languageNames[saved]) {
        current = saved;
      }
    },

    t(key) {
      const match = /^tpl(\d+)_name$/.exec(key);

      if (match) {
        const index = Number(match[1]) - 1;

        return (
          templateNames[current]?.[index] ??
          templateNames.en?.[index] ??
          key
        );
      }

      return ui[current]?.[key] ?? ui.en?.[key] ?? key;
    }
  };
}

export const lang = createLang();