const translations = {
  id: {
    nav_templates: 'Template', nav_create: 'Buat Invoice',
    hero_title: '100+ Template Invoice Gratis',
    hero_subtitle: 'Buat invoice profesional dalam hitungan menit. Pilih desain, isi data, langsung kirim.',
    hero_cta: 'Buat Invoice Sekarang!',
    gallery_title: 'Pilih Desain Invoice Kamu', gallery_subtitle: 'Mulai membuat invoice profesional dari sini!',
    see_all: 'Lihat Semua Template',
    f1_title: 'Buat Invoice', f1_desc: 'Pilih dari banyak template, tambahkan logo perusahaanmu.',
    f2_title: 'Kirim via Email', f2_desc: 'Kirim sebagai PDF langsung ke klien, atau cetak.',
    f3_title: 'Terima Pembayaran', f3_desc: 'Dapatkan pembayaran lebih cepat secara online.',
    footer: 'Dibuat untuk tugas kelompok — InvoiceKita 2026',
    tp_title: 'Pilih Template Invoice', tp_subtitle: '10 desain profesional, gratis untuk dipakai.',
    use_template: 'Gunakan template →',
  },
  en: {
    nav_templates: 'Templates', nav_create: 'Create Invoice',
    hero_title: '100+ Free Invoice Templates',
    hero_subtitle: 'Create a professional invoice in minutes. Pick a design, fill in the details, send it.',
    hero_cta: 'Create Invoice Now!',
    gallery_title: 'Choose Your Invoice Design', gallery_subtitle: 'Start creating your professional invoice here!',
    see_all: 'See All Templates',
    f1_title: 'Create an Invoice', f1_desc: 'Choose from many templates and add your company logo.',
    f2_title: 'Send via Email', f2_desc: 'Send as a PDF directly to your client, or print it.',
    f3_title: 'Get Paid', f3_desc: 'Receive payments faster online.',
    footer: 'Made for a group project — InvoiceKita 2026',
    tp_title: 'Choose an Invoice Template', tp_subtitle: '10 professional designs, free to use.',
    use_template: 'Use this template →',
  },
  es: {
    nav_templates: 'Plantillas', nav_create: 'Crear Factura',
    hero_title: '100+ Plantillas de Factura Gratis',
    hero_subtitle: 'Crea una factura profesional en minutos. Elige un diseño, completa los datos, envíala.',
    hero_cta: '¡Crear Factura Ahora!',
    gallery_title: 'Elige tu Diseño de Factura', gallery_subtitle: '¡Empieza a crear tu factura profesional aquí!',
    see_all: 'Ver Todas las Plantillas',
    f1_title: 'Crea una Factura', f1_desc: 'Elige entre varias plantillas y añade el logo de tu empresa.',
    f2_title: 'Envía por Email', f2_desc: 'Envía como PDF directamente a tu cliente, o imprímela.',
    f3_title: 'Recibe Pagos', f3_desc: 'Recibe pagos más rápido en línea.',
    footer: 'Hecho para un proyecto grupal — InvoiceKita 2026',
    tp_title: 'Elige una Plantilla de Factura', tp_subtitle: '10 diseños profesionales, gratis para usar.',
    use_template: 'Usar esta plantilla →',
  },
  fr: {
    nav_templates: 'Modèles', nav_create: 'Créer une Facture',
    hero_title: '100+ Modèles de Facture Gratuits',
    hero_subtitle: 'Créez une facture professionnelle en quelques minutes. Choisissez un modèle, remplissez les détails, envoyez-la.',
    hero_cta: 'Créer une Facture Maintenant !',
    gallery_title: 'Choisissez votre Modèle de Facture', gallery_subtitle: 'Commencez à créer votre facture professionnelle ici !',
    see_all: 'Voir Tous les Modèles',
    f1_title: 'Créer une Facture', f1_desc: 'Choisissez parmi de nombreux modèles et ajoutez le logo de votre entreprise.',
    f2_title: 'Envoyer par Email', f2_desc: 'Envoyez en PDF directement à votre client, ou imprimez-la.',
    f3_title: 'Soyez Payé', f3_desc: 'Recevez des paiements plus rapidement en ligne.',
    footer: 'Réalisé pour un projet de groupe — InvoiceKita 2026',
    tp_title: 'Choisissez un Modèle de Facture', tp_subtitle: '10 designs professionnels, gratuits à utiliser.',
    use_template: 'Utiliser ce modèle →',
  },
  de: {
    nav_templates: 'Vorlagen', nav_create: 'Rechnung Erstellen',
    hero_title: '100+ Kostenlose Rechnungsvorlagen',
    hero_subtitle: 'Erstellen Sie in wenigen Minuten eine professionelle Rechnung. Design wählen, Daten eingeben, senden.',
    hero_cta: 'Jetzt Rechnung Erstellen!',
    gallery_title: 'Wählen Sie Ihr Rechnungsdesign', gallery_subtitle: 'Beginnen Sie hier mit der Erstellung Ihrer professionellen Rechnung!',
    see_all: 'Alle Vorlagen Ansehen',
    f1_title: 'Rechnung Erstellen', f1_desc: 'Wählen Sie aus vielen Vorlagen und fügen Sie Ihr Firmenlogo hinzu.',
    f2_title: 'Per E-Mail Senden', f2_desc: 'Senden Sie als PDF direkt an Ihren Kunden oder drucken Sie sie aus.',
    f3_title: 'Bezahlt Werden', f3_desc: 'Erhalten Sie Zahlungen schneller online.',
    footer: 'Erstellt für ein Gruppenprojekt — InvoiceKita 2026',
    tp_title: 'Wählen Sie eine Rechnungsvorlage', tp_subtitle: '10 professionelle Designs, kostenlos nutzbar.',
    use_template: 'Vorlage verwenden →',
  },
  it: {
    nav_templates: 'Modelli', nav_create: 'Crea Fattura',
    hero_title: '100+ Modelli di Fattura Gratuiti',
    hero_subtitle: 'Crea una fattura professionale in pochi minuti. Scegli un design, inserisci i dati, invia.',
    hero_cta: 'Crea Fattura Ora!',
    gallery_title: 'Scegli il tuo Design della Fattura', gallery_subtitle: 'Inizia a creare la tua fattura professionale qui!',
    see_all: 'Vedi Tutti i Modelli',
    f1_title: 'Crea una Fattura', f1_desc: 'Scegli tra molti modelli e aggiungi il logo della tua azienda.',
    f2_title: 'Invia via Email', f2_desc: 'Invia come PDF direttamente al cliente, o stampala.',
    f3_title: 'Ricevi Pagamenti', f3_desc: 'Ricevi pagamenti più velocemente online.',
    footer: 'Realizzato per un progetto di gruppo — InvoiceKita 2026',
    tp_title: 'Scegli un Modello di Fattura', tp_subtitle: '10 design professionali, gratuiti da usare.',
    use_template: 'Usa questo modello →',
  },
  pt: {
    nav_templates: 'Modelos', nav_create: 'Criar Fatura',
    hero_title: '100+ Modelos de Fatura Grátis',
    hero_subtitle: 'Crie uma fatura profissional em minutos. Escolha um design, preencha os dados, envie.',
    hero_cta: 'Criar Fatura Agora!',
    gallery_title: 'Escolha o Design da sua Fatura', gallery_subtitle: 'Comece a criar sua fatura profissional aqui!',
    see_all: 'Ver Todos os Modelos',
    f1_title: 'Crie uma Fatura', f1_desc: 'Escolha entre vários modelos e adicione o logotipo da sua empresa.',
    f2_title: 'Envie por Email', f2_desc: 'Envie como PDF diretamente para o cliente, ou imprima.',
    f3_title: 'Receba Pagamentos', f3_desc: 'Receba pagamentos mais rápido online.',
    footer: 'Feito para um projeto em grupo — InvoiceKita 2026',
    tp_title: 'Escolha um Modelo de Fatura', tp_subtitle: '10 designs profissionais, grátis para usar.',
    use_template: 'Usar este modelo →',
  },
  ja: {
    nav_templates: 'テンプレート', nav_create: '請求書を作成',
    hero_title: '100種類以上の無料請求書テンプレート',
    hero_subtitle: '数分でプロ仕様の請求書を作成。デザインを選んで、情報を入力し、送信するだけ。',
    hero_cta: '今すぐ請求書を作成！',
    gallery_title: '請求書デザインを選択', gallery_subtitle: 'ここからプロの請求書作成を始めましょう！',
    see_all: 'すべてのテンプレートを見る',
    f1_title: '請求書を作成', f1_desc: '多数のテンプレートから選び、会社のロゴを追加。',
    f2_title: 'メールで送信', f2_desc: 'PDFとしてクライアントに直接送信、または印刷。',
    f3_title: '支払いを受け取る', f3_desc: 'オンラインでより早く支払いを受け取れます。',
    footer: 'グループプロジェクトのために作成 — InvoiceKita 2026',
    tp_title: '請求書テンプレートを選択', tp_subtitle: '10種類のプロデザイン、無料でご利用可能。',
    use_template: 'このテンプレートを使う →',
  },
  ko: {
    nav_templates: '템플릿', nav_create: '인보이스 만들기',
    hero_title: '100개 이상의 무료 인보이스 템플릿',
    hero_subtitle: '몇 분 만에 전문적인 인보이스를 만드세요. 디자인을 선택하고, 정보를 입력하고, 바로 보내세요.',
    hero_cta: '지금 인보이스 만들기!',
    gallery_title: '인보이스 디자인 선택하기', gallery_subtitle: '여기서 전문적인 인보이스 만들기를 시작하세요!',
    see_all: '모든 템플릿 보기',
    f1_title: '인보이스 만들기', f1_desc: '다양한 템플릿 중에서 선택하고 회사 로고를 추가하세요.',
    f2_title: '이메일로 보내기', f2_desc: 'PDF로 클라이언트에게 바로 보내거나 인쇄하세요.',
    f3_title: '결제 받기', f3_desc: '온라인으로 더 빠르게 결제를 받으세요.',
    footer: '그룹 프로젝트를 위해 제작 — InvoiceKita 2026',
    tp_title: '인보이스 템플릿 선택', tp_subtitle: '10가지 전문 디자인, 무료로 사용 가능.',
    use_template: '이 템플릿 사용하기 →',
  },
  zh: {
    nav_templates: '模板', nav_create: '创建发票',
    hero_title: '100多种免费发票模板',
    hero_subtitle: '几分钟内创建专业发票。选择设计，填写信息，直接发送。',
    hero_cta: '立即创建发票！',
    gallery_title: '选择您的发票设计', gallery_subtitle: '从这里开始创建您的专业发票！',
    see_all: '查看所有模板',
    f1_title: '创建发票', f1_desc: '从众多模板中选择，添加您的公司标志。',
    f2_title: '通过电子邮件发送', f2_desc: '以PDF格式直接发送给客户，或打印。',
    f3_title: '接收付款', f3_desc: '在线更快地收到付款。',
    footer: '为小组作业制作 — InvoiceKita 2026',
    tp_title: '选择发票模板', tp_subtitle: '10种专业设计，免费使用。',
    use_template: '使用此模板 →',
  },
};

const languageNames = {
  id: '🇮🇩 Indonesia', en: '🇬🇧 English', es: '🇪🇸 Español', fr: '🇫🇷 Français',
  de: '🇩🇪 Deutsch', it: '🇮🇹 Italiano', pt: '🇵🇹 Português', ja: '🇯🇵 日本語',
  ko: '🇰🇷 한국어', zh: '🇨🇳 中文',
};

function createLang() {
  let current = $state('id');

  return {
    get current() { return current; },
    get options() { return languageNames; },
    set(code) {
      current = code;
      localStorage.setItem('lang', code);
    },
    init() {
      const saved = localStorage.getItem('lang');
      if (saved && translations[saved]) current = saved;
    },
    t(key) {
      return translations[current]?.[key] ?? translations.en[key] ?? key;
    },
  };
}

export const lang = createLang();